EQUIPOS_POR_CLASE: dict[str, list[str]] = {
    "Soporte vital": [
        "Ventilador mecánico",
        "Máquina de anestesia",
        "Desfibrilador",
        "Bomba de infusión",
        "Bomba PCA",
    ],
    "Monitoreo": [
        "Monitor multiparámetro",
        "Electrocardiógrafo",
        "Oxímetro central",
        "Holter",
        "Monitor signos vitales",
    ],
    "Imagenología": [
        "Ecógrafo",
        "Rayos X portátil",
        "Arco C",
        "Mamógrafo",
        "Tomógrafo CT",
        "Resonador magnético",
    ],
    "Esterilización": [
        "Autoclave",
        "Lavadora desinfectora",
        "Selladora térmica",
        "Mesa de inspección",
        "Carro de transporte estéril",
    ],
    "Laboratorio": [
        "Centrífuga",
        "Analizador hematológico",
        "Microscopio",
        "Baño termorregulado",
        "Refrigerador clínico",
        "Analizador bioquímico",
    ],
    "Neonatología": [
        "Incubadora",
        "Cuna radiante",
        "Fototerapia",
        "Ventilador neonatal",
    ],
    "Odontología": [
        "Sillón dental",
        "Compresor dental",
        "Lámpara de fotocurado",
        "Motor endodoncia",
        "TAC dental",
        "Unidad dental",
    ],
    "Oftalmología": [
        "Lámpara de hendidura",
        "Tonómetro",
        "Autorrefractómetro",
        "Retinógrafo",
        "Campímetro",
        "OCT",
        "Lensómetro",
        "Microscopio quirúrgico oftalmológico",
    ],
    "Apoyo a diagnóstico": [
        "Esfigmomanómetro",
        "Bioimpedanciómetro",
        "Termómetro clínico",
        "Otoscopio",
        "Oftalmoscopio",
        "Doppler fetal",
        "Doppler vascular",
        "Glucómetro",
        "Espirómetro",
        "Audiómetro",
        "Balanza clínica",
        "Tallímetro",
        "Camilla de transporte",
    ],
    "Rehabilitación": [
        "Trotadora",
        "Camilla de fisioterapia",
        "Bicicleta ergométrica",
        "Electroestimulador",
    ],
}

CLASE_POR_EQUIPO: dict[str, str] = {
    equipo: clase for clase, lista in EQUIPOS_POR_CLASE.items() for equipo in lista
}


RANGO_COSTO_POR_EQUIPO: dict[str, tuple[int, int]] = {
    # Soporte Vital
    "Ventilador mecánico": (15_000_000, 45_000_000),
    "Máquina de anestesia": (25_000_000, 80_000_000),
    "Desfibrilador": (2_800_000, 8_500_000),
    "Bomba de infusión": (850_000, 2_500_000),
    "Bomba PCA": (1_500_000, 3_500_000),
    # Monitoreo
    "Monitor multiparámetro": (1_500_000, 6_500_000),
    "Electrocardiógrafo": (1_200_000, 4_500_000),
    "Oxímetro central": (1_500_000, 4_000_000),
    "Holter": (1_800_000, 5_000_000),
    "Monitor signos vitales": (700_000, 2_200_000),
    # Imagenología
    "Ecógrafo": (12_000_000, 65_000_000),
    "Rayos X portátil": (25_000_000, 70_000_000),
    "Arco C": (80_000_000, 250_000_000),
    "Mamógrafo": (120_000_000, 400_000_000),
    "Tomógrafo CT": (350_000_000, 900_000_000),
    "Resonador magnético": (500_000_000, 1_500_000_000),
    # Esterilización
    "Autoclave": (3_500_000, 48_000_000),
    "Lavadora desinfectora": (8_000_000, 32_000_000),
    "Selladora térmica": (600_000, 2_500_000),
    "Mesa de inspección": (800_000, 3_000_000),
    "Carro de transporte estéril": (800_000, 2_800_000),
    # Laboratorio
    "Centrífuga": (500_000, 5_000_000),
    "Analizador hematológico": (6_000_000, 25_000_000),
    "Microscopio": (600_000, 6_000_000),
    "Baño termorregulado": (400_000, 1_800_000),
    "Refrigerador clínico": (1_800_000, 7_500_000),
    "Analizador bioquímico": (12_000_000, 55_000_000),
    # Neonatología
    "Incubadora": (6_500_000, 22_000_000),
    "Cuna radiante": (4_500_000, 14_000_000),
    "Fototerapia": (1_500_000, 5_500_000),
    "Ventilador neonatal": (20_000_000, 55_000_000),
    # Odontología
    "Sillón dental": (3_500_000, 15_000_000),
    "Compresor dental": (800_000, 3_800_000),
    "Lámpara de fotocurado": (180_000, 850_000),
    "Motor endodoncia": (600_000, 2_500_000),
    "TAC dental": (45_000_000, 120_000_000),
    "Unidad dental": (4_500_000, 20_000_000),
    # Oftalmología
    "Lámpara de hendidura": (3_800_000, 16_000_000),
    "Tonómetro": (2_200_000, 7_500_000),
    "Autorrefractómetro": (4_500_000, 14_000_000),
    "Retinógrafo": (8_500_000, 32_000_000),
    "Campímetro": (10_000_000, 28_000_000),
    "OCT": (35_000_000, 85_000_000),
    "Lensómetro": (1_200_000, 4_500_000),
    "Microscopio quirúrgico oftalmológico": (28_000_000, 110_000_000),
    # Apoyo a diagnóstico
    "Esfigmomanómetro": (60_000, 350_000),
    "Bioimpedanciómetro": (1_200_000, 12_000_000),
    "Termómetro clínico": (10_000, 200_000),
    "Otoscopio": (120_000, 900_000),
    "Oftalmoscopio": (160_000, 1_000_000),
    "Doppler fetal": (180_000, 1_400_000),
    "Doppler vascular": (350_000, 2_800_000),
    "Glucómetro": (25_000, 80_000),
    "Espirómetro": (900_000, 3_500_000),
    "Audiómetro": (2_200_000, 7_500_000),
    "Balanza clínica": (180_000, 1_500_000),
    "Tallímetro": (50_000, 450_000),
    "Camilla de transporte": (2_000_000, 6_500_000),
    # Rehabilitación
    "Trotadora": (2_500_000, 8_000_000),
    "Camilla de fisioterapia": (400_000, 3_000_000),
    "Bicicleta ergométrica": (1_200_000, 5_000_000),
    "Electroestimulador": (500_000, 4_000_000),
}

CLASE_RIESGO_POR_EQUIPO: dict[str, str] = {
    # Soporte Vital
    "Ventilador mecánico": "III",
    "Máquina de anestesia": "III",
    "Desfibrilador": "III",
    "Bomba de infusión": "III",
    "Bomba PCA": "III",
    # Monitoreo
    "Monitor multiparámetro": "III",
    "Electrocardiógrafo": "II",
    "Oxímetro central": "III",
    "Holter": "II",
    "Monitor signos vitales": "II",
    # Imagenología
    "Ecógrafo": "II",
    "Rayos X portátil": "II",
    "Arco C": "II",
    "Mamógrafo": "II",
    "Tomógrafo CT": "II",
    "Resonador magnético": "II",
    # Esterilización
    "Autoclave": "II",
    "Lavadora desinfectora": "II",
    "Selladora térmica": "I",
    "Mesa de inspección": "I",
    "Carro de transporte estéril": "I",
    # Laboratorio
    "Centrífuga": "I",
    "Analizador hematológico": "II",
    "Microscopio": "I",
    "Baño termorregulado": "I",
    "Refrigerador clínico": "I",
    "Analizador bioquímico": "II",
    # Neonatología
    "Incubadora": "III",
    "Cuna radiante": "II",
    "Fototerapia": "II",
    "Ventilador neonatal": "III",
    # Odontología
    "Sillón dental": "I",
    "Compresor dental": "I",
    "Lámpara de fotocurado": "I",
    "Motor endodoncia": "II",
    "TAC dental": "II",
    "Unidad dental": "I",
    # Oftalmología
    "Lámpara de hendidura": "I",
    "Tonómetro": "II",
    "Autorrefractómetro": "I",
    "Retinógrafo": "II",
    "Campímetro": "II",
    "OCT": "II",
    "Lensómetro": "I",
    "Microscopio quirúrgico oftalmológico": "II",
    # Apoyo a diagnóstico
    "Esfigmomanómetro": "II",
    "Bioimpedanciómetro": "II",
    "Termómetro clínico": "II",
    "Otoscopio": "I",
    "Oftalmoscopio": "I",
    "Doppler fetal": "II",
    "Doppler vascular": "II",
    "Glucómetro": "II",
    "Espirómetro": "II",
    "Audiómetro": "II",
    "Balanza clínica": "I",
    "Tallímetro": "I",
    "Camilla de transporte": "I",
    # Rehabilitación
    "Trotadora": "I",
    "Camilla de fisioterapia": "I",
    "Bicicleta ergométrica": "I",
    "Electroestimulador": "II",
}

MARCAS_POR_EQUIPO: dict[str, list[str]] = {
    "Ventilador mecánico": [
        "Dräger",
        "Hamilton Medical",
        "GE HealthCare",
        "Mindray",
        "Philips",
    ],
    "Máquina de anestesia": [
        "Dräger",
        "GE HealthCare",
        "Mindray",
    ],
    "Desfibrilador": [
        "Philips",
        "ZOLL",
        "Stryker/Physio-Control",
        "Nihon Kohden",
        "Mindray",
    ],
    "Bomba de infusión": [
        "Baxter",
        "B. Braun",
        "Fresenius Kabi",
        "ICU Medical",
        "BD/CareFusion",
        "Mindray",
    ],
    "Bomba PCA": [
        "B. Braun",
        "Fresenius Kabi",
        "ICU Medical",
        "BD/CareFusion",
        "Baxter",
    ],
    "Monitor multiparámetro": [
        "Philips",
        "GE HealthCare",
        "Mindray",
        "Nihon Kohden",
        "Dräger",
        "Spacelabs",
        "Edan",
        "Bionet",
    ],
    "Electrocardiógrafo": [
        "Philips",
        "GE HealthCare",
        "Mindray",
        "Nihon Kohden",
        "Schiller",
        "Edan",
        "Bionet",
    ],
    "Oxímetro central": [
        "Masimo",
        "Nonin",
        "Philips",
        "GE HealthCare",
        "Mindray",
        "Nihon Kohden",
    ],
    "Holter": [
        "GE HealthCare",
        "Philips",
        "Nihon Kohden",
        "Schiller",
        "Spacelabs",
        "Bionet",
        "Edan",
    ],
    "Monitor signos vitales": [
        "Welch Allyn/Hillrom",
        "Philips",
        "GE HealthCare",
        "Mindray",
        "Nihon Kohden",
        "Edan",
        "Bionet",
        "Masimo",
        "Nonin",
    ],
    "Ecógrafo": [
        "GE HealthCare",
        "Philips",
        "Siemens Healthineers",
        "Canon Medical",
        "Fujifilm",
        "Samsung Medison",
        "Esaote",
        "Mindray",
        "United Imaging",
    ],
    "Rayos X portátil": [
        "GE HealthCare",
        "Philips",
        "Siemens Healthineers",
        "Canon Medical",
        "Fujifilm",
        "Shimadzu",
        "Carestream",
        "Konica Minolta",
        "United Imaging",
    ],
    "Arco C": [
        "GE HealthCare",
        "Philips",
        "Siemens Healthineers",
        "Shimadzu",
        "Ziehm Imaging",
        "Canon Medical",
    ],
    "Mamógrafo": [
        "GE HealthCare",
        "Siemens Healthineers",
        "Hologic",
        "Fujifilm",
        "Philips",
    ],
    "Tomógrafo CT": [
        "GE HealthCare",
        "Philips",
        "Siemens Healthineers",
        "Canon Medical",
        "United Imaging",
    ],
    "Resonador magnético": [
        "GE HealthCare",
        "Philips",
        "Siemens Healthineers",
        "Canon Medical",
        "United Imaging",
    ],
    "Autoclave": [
        "Getinge",
        "STERIS",
        "Matachana",
        "Tuttnauer",
        "Belimed",
        "Steelco",
        "MMM Group",
        "MELAG",
        "W&H",
        "CISA Group",
    ],
    "Lavadora desinfectora": [
        "Getinge",
        "STERIS",
        "Matachana",
        "Belimed",
        "Steelco",
        "MMM Group",
        "CISA Group",
    ],
    "Selladora térmica": [
        "hawo",
        "MELAG",
        "W&H",
        "Tuttnauer",
        "Matachana",
    ],
    "Mesa de inspección": [
        "Getinge",
        "STERIS",
        "Matachana",
        "Belimed",
        "Steelco",
        "MMM Group",
        "CISA Group",
    ],
    "Carro de transporte estéril": [
        "Getinge",
        "STERIS",
        "Matachana",
        "Belimed",
        "Steelco",
        "MMM Group",
        "CISA Group",
    ],
    "Centrífuga": [
        "Thermo Fisher Scientific",
        "Eppendorf",
        "Hettich",
        "Beckman Coulter",
    ],
    "Analizador hematológico": [
        "Sysmex",
        "Beckman Coulter",
        "Abbott",
        "Mindray",
        "Horiba",
        "Siemens Healthineers",
    ],
    "Microscopio": [
        "Zeiss",
        "Leica",
        "Olympus/Evident",
    ],
    "Baño termorregulado": [
        "Thermo Fisher Scientific",
        "Memmert",
        "Binder",
    ],
    "Refrigerador clínico": [
        "PHCbi",
        "Haier Biomedical",
        "Helmer",
        "Thermo Fisher Scientific",
        "Binder",
    ],
    "Analizador bioquímico": [
        "Roche",
        "Abbott",
        "Beckman Coulter",
        "Siemens Healthineers",
        "Mindray",
        "Horiba",
    ],
    "Incubadora": [
        "Dräger",
        "GE HealthCare/Ohmeda",
        "Fanem",
        "Medix",
        "Atom Medical",
    ],
    "Cuna radiante": [
        "Dräger",
        "GE HealthCare/Ohmeda",
        "Fanem",
        "Medix",
        "Atom Medical",
    ],
    "Fototerapia": [
        "Fanem",
        "Medix",
        "Natus",
        "Atom Medical",
        "GE HealthCare/Ohmeda",
        "Dräger",
    ],
    "Ventilador neonatal": [
        "Dräger",
        "Hamilton Medical",
        "SLE",
        "Vyaire",
        "Inspiration Healthcare",
    ],
    "Sillón dental": [
        "A-dec",
        "KaVo",
        "Gnatus",
        "Dentsply Sirona",
        "Planmeca",
        "Morita",
        "Belmont",
    ],
    "Compresor dental": [
        "Dürr Dental",
        "Gnatus",
        "W&H",
        "KaVo",
    ],
    "Lámpara de fotocurado": [
        "Woodpecker",
        "Dentsply Sirona",
        "Acteon/Satelec",
        "W&H",
        "KaVo",
    ],
    "Motor endodoncia": [
        "Woodpecker",
        "Morita",
        "Dentsply Sirona",
        "NSK",
        "W&H",
        "KaVo",
    ],
    "TAC dental": [
        "Morita",
        "Planmeca",
        "Vatech",
        "NewTom",
        "Carestream Dental",
        "Dentsply Sirona",
    ],
    "Unidad dental": [
        "A-dec",
        "KaVo",
        "Gnatus",
        "Dentsply Sirona",
        "Planmeca",
        "Morita",
        "Belmont",
    ],
    "Lámpara de hendidura": [
        "Topcon",
        "Haag-Streit",
        "Zeiss",
        "Nidek",
        "Keeler",
        "Kowa",
        "Huvitz",
        "Tomey",
    ],
    "Tonómetro": [
        "Topcon",
        "Haag-Streit",
        "Reichert",
        "Keeler",
        "Nidek",
        "Canon",
        "Huvitz",
        "Tomey",
    ],
    "Autorrefractómetro": [
        "Topcon",
        "Nidek",
        "Canon",
        "Reichert",
        "Huvitz",
        "Tomey",
        "Kowa",
    ],
    "Retinógrafo": [
        "Topcon",
        "Zeiss",
        "Canon",
        "Nidek",
        "Heidelberg Engineering",
        "Kowa",
    ],
    "Campímetro": [
        "Zeiss",
        "Topcon",
        "Oculus",
        "Haag-Streit",
    ],
    "OCT": [
        "Zeiss",
        "Heidelberg Engineering",
        "Topcon",
        "Nidek",
        "Canon",
    ],
    "Lensómetro": [
        "Topcon",
        "Nidek",
        "Reichert",
        "Huvitz",
        "Tomey",
        "Canon",
    ],
    "Microscopio quirúrgico oftalmológico": [
        "Zeiss",
        "Leica Microsystems",
        "Haag-Streit",
    ],
    "Esfigmomanómetro": [
        "Welch Allyn/Hillrom",
        "Riester",
        "Omron",
        "Microlife",
        "A&D Medical",
        "Gima",
    ],
    "Bioimpedanciómetro": [
        "SECA",
        "InBody",
        "Tanita",
    ],
    "Termómetro clínico": [
        "Welch Allyn/Hillrom",
        "Braun",
        "Omron",
        "Microlife",
        "Riester",
        "Gima",
    ],
    "Otoscopio": [
        "Welch Allyn/Hillrom",
        "Riester",
        "HEINE",
        "Gima",
    ],
    "Oftalmoscopio": [
        "Welch Allyn/Hillrom",
        "Riester",
        "HEINE",
        "Gima",
    ],
    "Doppler fetal": [
        "Edan",
        "Huntleigh",
        "Gima",
    ],
    "Doppler vascular": [
        "Huntleigh",
        "Edan",
        "Gima",
    ],
    "Glucómetro": [
        "Roche/Accu-Chek",
        "Abbott",
        "Gima",
    ],
    "Espirómetro": [
        "MIR",
        "Vitalograph",
        "ndd",
        "Vyaire/CareFusion",
        "Welch Allyn/Hillrom",
        "Gima",
    ],
    "Audiómetro": [
        "Interacoustics",
        "MAICO",
        "Inventis",
        "Gima",
    ],
    "Balanza clínica": [
        "SECA",
        "Detecto",
        "Health o meter",
        "Tanita",
        "Gima",
    ],
    "Tallímetro": [
        "SECA",
        "Detecto",
        "Health o meter",
        "Tanita",
        "Gima",
    ],
    "Camilla de transporte": [
        "Malvestio",
        "Hillrom/Baxter",
        "Stryker/Physio-Control",
    ],
    "Trotadora": [
        "Technogym",
        "Life Fitness",
        "Woodway",
        "Biodex",
        "SCIFIT",
    ],
    "Camilla de fisioterapia": [
        "Lojer",
        "Chattanooga",
        "Gymna",
        "BTL",
        "Enraf-Nonius",
    ],
    "Bicicleta ergométrica": [
        "Technogym",
        "SCIFIT",
        "Monark",
        "Biodex",
    ],
    "Electroestimulador": [
        "Chattanooga",
        "Enraf-Nonius",
        "BTL",
        "Zimmer MedizinSysteme",
        "DJO/Compex",
        "Gymna",
        "I-TECH",
        "Globus",
    ],
}


FALLAS_POR_EQUIPO: dict[str, list[str]] = {
    "Ventilador mecánico": [
        "No enciende",
        "Fuga en circuito",
        "Alarma de presión",
        "Falla de batería",
        "Sensor defectuoso",
        "Error de calibración",
        "Falla de pantalla",
        "Problema en válvulas internas",
    ],
    "Máquina de anestesia": [
        "Fuga de gases",
        "Falla en vaporizador",
        "Error en sensor de oxígeno",
        "Problema en ventilador integrado",
        "Alarma de presión",
        "Falla de batería",
        "Pantalla sin respuesta",
    ],
    "Desfibrilador": [
        "No carga energía",
        "Descarga fallida",
        "Batería agotada",
        "Palas/electrodos defectuosos",
        "Error de autoprueba",
        "Pantalla dañada",
        "Impresora no funciona",
    ],
    "Bomba de infusión": [
        "No detecta línea",
        "Alarma de oclusión",
        "Caudal incorrecto",
        "Batería dañada",
        "Teclado/pantalla defectuosa",
        "Puerta o clamp dañado",
        "Error de calibración",
    ],
    "Bomba PCA": [
        "Error de programación",
        "Botón de paciente defectuoso",
        "Alarma de oclusión",
        "Batería agotada",
        "Caudal incorrecto",
        "Bloqueo de seguridad dañado",
    ],
    "Monitor multiparámetro": [
        "No enciende",
        "Pantalla sin imagen",
        "Lecturas erráticas",
        "Módulo ECG dañado",
        "SpO₂ no detecta señal",
        "NIBP no infla",
        "Alarmas defectuosas",
    ],
    "Electrocardiógrafo": [
        "Trazado con ruido",
        "Electrodos/cables dañados",
        "Impresora no imprime",
        "Batería agotada",
        "Error de calibración",
        "Pantalla defectuosa",
    ],
    "Oxímetro central": [
        "No detecta sensor",
        "Lectura inestable",
        "Cable o sensor dañado",
        "Alarma no funciona",
        "Problema de comunicación con central",
    ],
    "Holter": [
        "No registra datos",
        "Batería dañada",
        "Cables de paciente defectuosos",
        "Memoria llena",
        "Error de descarga de datos",
        "Software no reconoce el equipo",
    ],
    "Monitor signos vitales": [
        "Falla de presión NIBP",
        "SpO₂ sin lectura",
        "Temperatura errática",
        "Batería defectuosa",
        "Pantalla dañada",
        "Alarmas inoperativas",
    ],
    "Ecógrafo": [
        "Imagen con ruido",
        "Transductor dañado",
        "Congelamiento del software",
        "Pantalla defectuosa",
        "Puertos dañados",
        "Falla de teclado o trackball",
    ],
    "Rayos X portátil": [
        "No genera exposición",
        "Batería defectuosa",
        "Error de colimador",
        "Falla de detector",
        "Imagen subexpuesta",
        "Problema de comunicación con estación",
    ],
    "Arco C": [
        "Imagen distorsionada",
        "Falla de fluoroscopía",
        "Error de movimiento del arco",
        "Detector defectuoso",
        "Pedal dañado",
        "Sobrecalentamiento",
    ],
    "Mamógrafo": [
        "Compresor mamario no funciona",
        "Imagen con artefactos",
        "Error de detector",
        "Falla de exposición",
        "Problemas de calibración",
    ],
    "Tomógrafo CT": [
        "Error de gantry",
        "Sobrecalentamiento del tubo",
        "Falla de detector",
        "Artefactos de imagen",
        "Problemas de mesa",
        "Error de software",
    ],
    "Resonador magnético": [
        "Fallas de bobina",
        "Artefactos de imagen",
        "Error de criogenia",
        "Problemas de gradientes",
        "Falla de comunicación",
        "Error de software",
    ],
    "Autoclave": [
        "No alcanza temperatura",
        "No genera presión",
        "Fuga de vapor",
        "Ciclo incompleto",
        "Puerta no sella",
        "Error de sensores",
        "Falla de resistencia",
    ],
    "Lavadora desinfectora": [
        "No calienta agua",
        "Bomba de lavado defectuosa",
        "Boquillas obstruidas",
        "Puerta no cierra",
        "Dosificación incorrecta de detergente",
    ],
    "Selladora térmica": [
        "No sella correctamente",
        "Temperatura inestable",
        "Rodillos gastados",
        "Resistencia dañada",
        "Cinta o bolsa mal arrastrada",
    ],
    "Mesa de inspección": [
        "Iluminación defectuosa",
        "Superficie dañada",
        "Enchufes sin energía",
        "Accesorios sueltos",
    ],
    "Carro de transporte estéril": [
        "Ruedas dañadas",
        "Frenos defectuosos",
        "Puertas o cierres sueltos",
        "Corrosión",
        "Bandejas deformadas",
    ],
    "Centrífuga": [
        "Vibración excesiva",
        "Rotor desbalanceado",
        "Tapa no bloquea",
        "No alcanza RPM",
        "Error de motor",
        "Ruido anormal",
    ],
    "Analizador hematológico": [
        "Obstrucción de líneas",
        "Error de reactivo",
        "Resultados fuera de rango",
        "Falla de aspiración",
        "Error de calibración",
        "Problemas de control de calidad",
    ],
    "Microscopio": [
        "Imagen borrosa",
        "Iluminación defectuosa",
        "Lentes sucios o dañados",
        "Enfoque trabado",
        "Platina desalineada",
    ],
    "Baño termorregulado": [
        "Temperatura inestable",
        "Resistencia dañada",
        "Sensor defectuoso",
        "Fuga de agua",
        "Display no funciona",
    ],
    "Refrigerador clínico": [
        "Temperatura fuera de rango",
        "Alarma defectuosa",
        "Puerta no sella",
        "Condensador sucio",
        "Falla de compresor",
        "Registro de temperatura incorrecto",
    ],
    "Analizador bioquímico": [
        "Error de reactivos",
        "Obstrucción de pipetas",
        "Resultados inconsistentes",
        "Falla de calibración",
        "Problemas de lavado",
        "Error de software",
    ],
    "Incubadora": [
        "Temperatura inestable",
        "Sensor de humedad defectuoso",
        "Alarma no funciona",
        "Falla de ventilador",
        "Puerta o cúpula dañada",
    ],
    "Cuna radiante": [
        "No calienta",
        "Sensor de piel defectuoso",
        "Alarma de temperatura",
        "Lámpara/resistencia dañada",
        "Falla de control",
    ],
    "Fototerapia": [
        "Baja intensidad lumínica",
        "Lámparas/LED dañados",
        "Temporizador defectuoso",
        "Irradiancia fuera de rango",
        "Pantalla dañada",
    ],
    "Ventilador neonatal": [
        "Fuga en circuito",
        "Sensor de flujo defectuoso",
        "Presión inestable",
        "Alarma de apnea",
        "Batería dañada",
        "Error de calibración",
    ],
    "Sillón dental": [
        "No sube/baja",
        "Pedal defectuoso",
        "Fuga hidráulica/neumática",
        "Lámpara no funciona",
        "Tapiz dañado",
        "Ruidos mecánicos",
    ],
    "Compresor dental": [
        "No genera presión",
        "Fuga de aire",
        "Ruido excesivo",
        "Filtro saturado",
        "Condensación excesiva",
        "Motor no arranca",
    ],
    "Lámpara de fotocurado": [
        "Baja intensidad",
        "Batería defectuosa",
        "Punta dañada",
        "Temporizador falla",
        "LED agotado",
    ],
    "Motor endodoncia": [
        "No gira",
        "Torque incorrecto",
        "Batería dañada",
        "Contraángulo defectuoso",
        "Pedal o botón fallando",
    ],
    "TAC dental": [
        "Imagen con artefactos",
        "Error de sensor",
        "Falla de rotación",
        "Problema de software",
        "Mala calibración",
        "Comunicación fallida",
    ],
    "Unidad dental": [
        "Fuga de agua/aire",
        "Pieza de mano sin presión",
        "Pedal defectuoso",
        "Succión deficiente",
        "Lámpara dañada",
        "Mangueras deterioradas",
    ],
    "Lámpara de hendidura": [
        "Iluminación débil",
        "Enfoque defectuoso",
        "Joystick trabado",
        "Óptica sucia",
        "Base desalineada",
    ],
    "Tonómetro": [
        "Lectura incorrecta",
        "Error de calibración",
        "Punta/sensor dañado",
        "Batería agotada",
        "Pantalla defectuosa",
    ],
    "Autorrefractómetro": [
        "Lecturas inconsistentes",
        "Error de alineación",
        "Pantalla dañada",
        "Joystick defectuoso",
        "Impresora no funciona",
    ],
    "Retinógrafo": [
        "Imagen borrosa",
        "Flash defectuoso",
        "Cámara no captura",
        "Error de enfoque",
        "Software no guarda imágenes",
    ],
    "Campímetro": [
        "Botón de respuesta defectuoso",
        "Pantalla/proyector con falla",
        "Resultados inconsistentes",
        "Error de calibración",
    ],
    "OCT": [
        "Imagen con artefactos",
        "Error de escaneo",
        "Mala alineación",
        "Fallo de software",
        "Cámara/sensor defectuoso",
    ],
    "Lensómetro": [
        "Lectura incorrecta",
        "Error de calibración",
        "Pantalla dañada",
        "Sensor óptico sucio",
        "Impresora defectuosa",
    ],
    "Microscopio quirúrgico oftalmológico": [
        "Iluminación defectuosa",
        "Enfoque motorizado falla",
        "Brazo desbalanceado",
        "Óptica dañada",
        "Pedal defectuoso",
    ],
    "Esfigmomanómetro": [
        "Lectura incorrecta",
        "Fuga en brazalete",
        "Pera dañada",
        "Válvula defectuosa",
        "Manómetro descalibrado",
    ],
    "Bioimpedanciómetro": [
        "Lecturas inconsistentes",
        "Electrodos defectuosos",
        "Error de calibración",
        "Pantalla dañada",
        "Problemas de software",
    ],
    "Termómetro clínico": [
        "Lectura errática",
        "Batería agotada",
        "Sensor dañado",
        "Tiempo de medición excesivo",
        "Pantalla defectuosa",
    ],
    "Otoscopio": [
        "Luz débil",
        "Batería dañada",
        "Lente sucio o rayado",
        "Cabezal flojo",
        "Contacto eléctrico defectuoso",
    ],
    "Oftalmoscopio": [
        "Iluminación deficiente",
        "Batería dañada",
        "Selector de lentes trabado",
        "Óptica sucia",
    ],
    "Doppler fetal": [
        "No detecta latido",
        "Sonda defectuosa",
        "Audio distorsionado",
        "Batería agotada",
        "Pantalla dañada",
    ],
    "Doppler vascular": [
        "Señal débil",
        "Sonda dañada",
        "Audio defectuoso",
        "Batería agotada",
        "Error de frecuencia",
    ],
    "Glucómetro": [
        "Lecturas erróneas",
        "Tiras no reconocidas",
        "Batería agotada",
        "Puerto sucio",
        "Error de codificación o control",
    ],
    "Espirómetro": [
        "Lecturas inconsistentes",
        "Sensor de flujo sucio",
        "Boquilla obstruida",
        "Error de calibración",
        "Software no registra",
    ],
    "Audiómetro": [
        "Tonos no se emiten",
        "Auriculares defectuosos",
        "Calibración vencida",
        "Botón de paciente dañado",
        "Ruido/interferencia",
    ],
    "Balanza clínica": [
        "Peso incorrecto",
        "Celda de carga dañada",
        "Display defectuoso",
        "Batería agotada",
        "Plataforma desnivelada",
    ],
    "Tallímetro": [
        "Medición imprecisa",
        "Guía trabada",
        "Piezas sueltas",
        "Escala dañada",
    ],
    "Camilla de transporte": [
        "Ruedas trabadas",
        "Frenos defectuosos",
        "Barandas sueltas",
        "Sistema hidráulico con fuga",
        "Colchón dañado",
        "Mecanismo de altura no funciona",
    ],
    "Trotadora": [
        "Banda desalineada",
        "Motor falla",
        "Velocidad inestable",
        "Botón de emergencia defectuoso",
        "Ruido mecánico",
    ],
    "Camilla de fisioterapia": [
        "Sistema de altura no funciona",
        "Tapiz dañado",
        "Ruedas/frenos defectuosos",
        "Estructura inestable",
    ],
    "Bicicleta ergométrica": [
        "Resistencia no regula",
        "Pedales dañados",
        "Pantalla defectuosa",
        "Sensor de velocidad falla",
        "Ruido mecánico",
    ],
    "Electroestimulador": [
        "No entrega corriente",
        "Cables/electrodos dañados",
        "Intensidad inestable",
        "Batería defectuosa",
        "Canales inoperativos",
    ],
}


SERVICIOS_CLINICOS: list[str] = [
    "Urgencia",
    "UCI Adulto",
    "UTI / Cuidados Intermedios",
    "Pabellón Quirúrgico",
    "Hospitalización",
    "Medicina Interna",
    "Cirugía",
    "Traumatología",
    "Cardiología",
    "Ginecología y Obstetricia",
    "Neonatología",
    "Pediatría",
    "Imagenología",
    "Laboratorio Clínico",
    "Esterilización",
    "Farmacia",
    "Endoscopía",
    "Kinesiología / Rehabilitación",
    "Odontología",
    "Oftalmología",
    "Corta estancia",
    "Hospital de Día",
    "Bodega",
    "Cuidados Paliativos",
]

UBICACION_POR_SERVICIO: dict[str, tuple[str, int]] = {
    "Urgencia": ("A", 1),
    "UCI Adulto": ("A", 3),
    "UTI / Cuidados Intermedios": ("B", 3),
    "Pabellón Quirúrgico": ("A", 2),
    "Hospitalización": ("B", 4),
    "Medicina Interna": ("B", 5),
    "Cirugía": ("B", 6),
    "Traumatología": ("B", 6),
    "Cardiología": ("A", 4),
    "Ginecología y Obstetricia": ("B", 2),
    "Neonatología": ("B", 3),
    "Pediatría": ("B", 4),
    "Imagenología": ("A", 2),
    "Laboratorio Clínico": ("A", 6),
    "Esterilización": ("D", 2),
    "Farmacia": ("A", 1),
    "Endoscopía": ("A", 5),
    "Kinesiología / Rehabilitación": ("C", 1),
    "Odontología": ("C", 2),
    "Oftalmología": ("C", 3),
    "Corta estancia": ("A", 1),
    "Hospital de Día": ("C", 1),
    "Bodega": ("D", 1),
    "Cuidados Paliativos": ("B", 7),
}

SERVICIOS_POR_CLASE: dict[str, list[str]] = {
    "Soporte vital": [
        "UCI Adulto",
        "UTI / Cuidados Intermedios",
        "Urgencia",
        "Pabellón Quirúrgico",
        "Cirugía",
        "Corta estancia",
        "Cardiología",
        "Ginecología y Obstetricia",
        "Neonatología",
        "Pediatría",
        "Endoscopía",
    ],
    "Monitoreo": [
        "Urgencia",
        "UCI Adulto",
        "UTI / Cuidados Intermedios",
        "Pabellón Quirúrgico",
        "Hospitalización",
        "Medicina Interna",
        "Cirugía",
        "Traumatología",
        "Cardiología",
        "Ginecología y Obstetricia",
        "Neonatología",
        "Pediatría",
        "Corta estancia",
        "Hospital de Día",
        "Endoscopía",
        "Cuidados Paliativos",
    ],
    "Imagenología": [
        "Imagenología",
        "Urgencia",
        "Pabellón Quirúrgico",
        "Traumatología",
        "Cardiología",
        "Ginecología y Obstetricia",
        "Endoscopía",
    ],
    "Esterilización": [
        "Esterilización",
    ],
    "Laboratorio": [
        "Laboratorio Clínico",
        "Farmacia",
        "Pabellón Quirúrgico",
        "UTI / Cuidados Intermedios",
        "Hospitalización",
        "Medicina Interna",
        "Cardiología",
        "Pediatría",
        "Hospital de Día",
    ],
    "Neonatología": [
        "Neonatología",
        "Ginecología y Obstetricia",
        "Pediatría",
        "Urgencia",
    ],
    "Odontología": [
        "Odontología",
    ],
    "Oftalmología": [
        "Oftalmología",
    ],
    "Apoyo a diagnóstico": [
        "Urgencia",
        "UCI Adulto",
        "UTI / Cuidados Intermedios",
        "Pabellón Quirúrgico",
        "Hospitalización",
        "Medicina Interna",
        "Cirugía",
        "Traumatología",
        "Cardiología",
        "Ginecología y Obstetricia",
        "Neonatología",
        "Pediatría",
        "Imagenología",
        "Laboratorio Clínico",
        "Farmacia",
        "Endoscopía",
        "Kinesiología / Rehabilitación",
        "Odontología",
        "Oftalmología",
        "Corta estancia",
        "Hospital de Día",
        "Cuidados Paliativos",
    ],
    "Rehabilitación": [
        "Kinesiología / Rehabilitación",
    ],
}


ESPECIALIDAD_POR_CLASE: dict[str, str] = {
    "Soporte vital": "Biomédico",
    "Monitoreo": "Biomédico",
    "Imagenología": "Imagenología y Radiología",
    "Esterilización": "Mecatrónica",
    "Laboratorio": "Laboratorio",
    "Neonatología": "Biomédico",
    "Odontología": "Mecatrónica",
    "Oftalmología": "Imagenología y Radiología",
    "Apoyo a diagnóstico": "Biomédico",
    "Rehabilitación": "Mecatrónica",
}

# Peso relativo de abundancia
ABUNDANCIA_POR_EQUIPO: dict[str, int] = {
    "Ventilador mecánico": 25,
    "Máquina de anestesia": 12,
    "Desfibrilador": 25,
    "Bomba de infusión": 100,
    "Bomba PCA": 12,
    "Monitor multiparámetro": 70,
    "Electrocardiógrafo": 18,
    "Oxímetro central": 8,
    "Holter": 4,
    "Monitor signos vitales": 40,
    "Ecógrafo": 18,
    "Rayos X portátil": 6,
    "Arco C": 4,
    "Mamógrafo": 1,
    "Tomógrafo CT": 2,
    "Resonador magnético": 1,
    "Autoclave": 5,
    "Lavadora desinfectora": 4,
    "Selladora térmica": 8,
    "Mesa de inspección": 5,
    "Carro de transporte estéril": 18,
    "Centrífuga": 12,
    "Analizador hematológico": 4,
    "Microscopio": 8,
    "Baño termorregulado": 5,
    "Refrigerador clínico": 10,
    "Analizador bioquímico": 4,
    "Incubadora": 14,
    "Cuna radiante": 10,
    "Fototerapia": 9,
    "Ventilador neonatal": 7,
    "Sillón dental": 4,
    "Compresor dental": 2,
    "Lámpara de fotocurado": 5,
    "Motor endodoncia": 3,
    "TAC dental": 1,
    "Unidad dental": 4,
    "Lámpara de hendidura": 3,
    "Tonómetro": 3,
    "Autorrefractómetro": 2,
    "Retinógrafo": 1,
    "Campímetro": 1,
    "OCT": 1,
    "Lensómetro": 1,
    "Microscopio quirúrgico oftalmológico": 1,
    "Esfigmomanómetro": 70,
    "Bioimpedanciómetro": 3,
    "Termómetro clínico": 75,
    "Otoscopio": 20,
    "Oftalmoscopio": 18,
    "Doppler fetal": 8,
    "Doppler vascular": 4,
    "Glucómetro": 45,
    "Espirómetro": 4,
    "Audiómetro": 2,
    "Balanza clínica": 30,
    "Tallímetro": 20,
    "Camilla de transporte": 45,
    "Trotadora": 2,
    "Camilla de fisioterapia": 10,
    "Bicicleta ergométrica": 4,
    "Electroestimulador": 7,
}
